[2023-07-10 20:20:46,817] INFO _log() L224   * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.15.7:5000 (Press CTRL+C to quit) - call_trace=C:\Users\Lucas\dev\Pos Eng Soft Puc RJ\mvp-1\api\env\Lib\site-packages\werkzeug\_internal.py L224 
[2023-07-10 20:20:46,825] INFO _log() L224   * Restarting with stat - call_trace=C:\Users\Lucas\dev\Pos Eng Soft Puc RJ\mvp-1\api\env\Lib\site-packages\werkzeug\_internal.py L224 
[2023-07-10 20:22:18,038] INFO _log() L224   * Detected change in 'C:\\Users\\Lucas\\dev\\Pos Eng Soft Puc RJ\\mvp-1\\api\\app.py', reloading - call_trace=C:\Users\Lucas\dev\Pos Eng Soft Puc RJ\mvp-1\api\env\Lib\site-packages\werkzeug\_internal.py L224 
[2023-07-10 20:22:18,198] INFO _log() L224   * Restarting with stat - call_trace=C:\Users\Lucas\dev\Pos Eng Soft Puc RJ\mvp-1\api\env\Lib\site-packages\werkzeug\_internal.py L224 
[2023-07-10 20:22:28,618] INFO _log() L224  127.0.0.1 - - [10/Jul/2023 20:22:28] "OPTIONS /schedule HTTP/1.1" 200 - - call_trace=C:\Users\Lucas\dev\Pos Eng Soft Puc RJ\mvp-1\api\env\Lib\site-packages\werkzeug\_internal.py L224 
[2023-07-10 20:22:28,874] ERROR log_exception() L1449 Exception on /schedule [POST] - call_trace=C:\Users\Lucas\dev\Pos Eng Soft Puc RJ\mvp-1\api\env\Lib\site-packages\flask\app.py L1449
Traceback (most recent call last):
  File "C:\Users\Lucas\dev\Pos Eng Soft Puc RJ\mvp-1\api\env\Lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lucas\dev\Pos Eng Soft Puc RJ\mvp-1\api\env\Lib\site-packages\flask\app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lucas\dev\Pos Eng Soft Puc RJ\mvp-1\api\env\Lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lucas\dev\Pos Eng Soft Puc RJ\mvp-1\api\env\Lib\site-packages\flask\app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lucas\dev\Pos Eng Soft Puc RJ\mvp-1\api\env\Lib\site-packages\flask\app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lucas\dev\Pos Eng Soft Puc RJ\mvp-1\api\env\Lib\site-packages\flask_openapi3\scaffold.py", line 191, in wrapper
    resp = _do_wrapper(
           ^^^^^^^^^^^^
  File "C:\Users\Lucas\dev\Pos Eng Soft Puc RJ\mvp-1\api\env\Lib\site-packages\flask_openapi3\do_wrapper.py", line 135, in _do_wrapper
    response = func(**request_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lucas\dev\Pos Eng Soft Puc RJ\mvp-1\api\app.py", line 141, in add_schedule
    print("JSON:  " + form.json)
          ~~~~~~~~~~^~~~~~~~~~~
TypeError: can only concatenate str (not "method") to str
[2023-07-10 20:22:28,894] INFO _log() L224  127.0.0.1 - - [10/Jul/2023 20:22:28] "[35m[1mPOST /schedule HTTP/1.1[0m" 500 - - call_trace=C:\Users\Lucas\dev\Pos Eng Soft Puc RJ\mvp-1\api\env\Lib\site-packages\werkzeug\_internal.py L224 
[2023-07-10 20:22:44,541] INFO _log() L224   * Detected change in 'C:\\Users\\Lucas\\dev\\Pos Eng Soft Puc RJ\\mvp-1\\api\\app.py', reloading - call_trace=C:\Users\Lucas\dev\Pos Eng Soft Puc RJ\mvp-1\api\env\Lib\site-packages\werkzeug\_internal.py L224 
[2023-07-10 20:22:44,674] INFO _log() L224   * Restarting with stat - call_trace=C:\Users\Lucas\dev\Pos Eng Soft Puc RJ\mvp-1\api\env\Lib\site-packages\werkzeug\_internal.py L224 
[2023-07-10 20:22:48,315] INFO _log() L224  127.0.0.1 - - [10/Jul/2023 20:22:48] "OPTIONS /schedule HTTP/1.1" 200 - - call_trace=C:\Users\Lucas\dev\Pos Eng Soft Puc RJ\mvp-1\api\env\Lib\site-packages\werkzeug\_internal.py L224 
[2023-07-10 20:22:48,583] ERROR log_exception() L1449 Exception on /schedule [POST] - call_trace=C:\Users\Lucas\dev\Pos Eng Soft Puc RJ\mvp-1\api\env\Lib\site-packages\flask\app.py L1449
Traceback (most recent call last):
  File "C:\Users\Lucas\dev\Pos Eng Soft Puc RJ\mvp-1\api\env\Lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lucas\dev\Pos Eng Soft Puc RJ\mvp-1\api\env\Lib\site-packages\flask\app.py", line 1520, in full_dispatch_request
    return self.finalize_request(rv)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lucas\dev\Pos Eng Soft Puc RJ\mvp-1\api\env\Lib\site-packages\flask\app.py", line 1539, in finalize_request
    response = self.make_response(rv)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lucas\dev\Pos Eng Soft Puc RJ\mvp-1\api\env\Lib\site-packages\flask\app.py", line 1730, in make_response
    raise TypeError(
TypeError: The view function did not return a valid response. The return type must be a string, dict, tuple, Response instance, or WSGI callable, but it was a ScheduleViewSchema.
[2023-07-10 20:22:48,591] INFO _log() L224  127.0.0.1 - - [10/Jul/2023 20:22:48] "[35m[1mPOST /schedule HTTP/1.1[0m" 500 - - call_trace=C:\Users\Lucas\dev\Pos Eng Soft Puc RJ\mvp-1\api\env\Lib\site-packages\werkzeug\_internal.py L224 
[2023-07-10 20:23:28,409] INFO _log() L224   * Detected change in 'C:\\Users\\Lucas\\dev\\Pos Eng Soft Puc RJ\\mvp-1\\api\\app.py', reloading - call_trace=C:\Users\Lucas\dev\Pos Eng Soft Puc RJ\mvp-1\api\env\Lib\site-packages\werkzeug\_internal.py L224 
[2023-07-10 20:23:28,550] INFO _log() L224   * Restarting with stat - call_trace=C:\Users\Lucas\dev\Pos Eng Soft Puc RJ\mvp-1\api\env\Lib\site-packages\werkzeug\_internal.py L224 
[2023-07-10 20:23:30,949] INFO _log() L224  127.0.0.1 - - [10/Jul/2023 20:23:30] "OPTIONS /schedule HTTP/1.1" 200 - - call_trace=C:\Users\Lucas\dev\Pos Eng Soft Puc RJ\mvp-1\api\env\Lib\site-packages\werkzeug\_internal.py L224 
[2023-07-10 20:23:31,213] ERROR log_exception() L1449 Exception on /schedule [POST] - call_trace=C:\Users\Lucas\dev\Pos Eng Soft Puc RJ\mvp-1\api\env\Lib\site-packages\flask\app.py L1449
Traceback (most recent call last):
  File "C:\Users\Lucas\dev\Pos Eng Soft Puc RJ\mvp-1\api\env\Lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lucas\dev\Pos Eng Soft Puc RJ\mvp-1\api\env\Lib\site-packages\flask\app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lucas\dev\Pos Eng Soft Puc RJ\mvp-1\api\env\Lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lucas\dev\Pos Eng Soft Puc RJ\mvp-1\api\env\Lib\site-packages\flask\app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lucas\dev\Pos Eng Soft Puc RJ\mvp-1\api\env\Lib\site-packages\flask\app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lucas\dev\Pos Eng Soft Puc RJ\mvp-1\api\env\Lib\site-packages\flask_openapi3\scaffold.py", line 191, in wrapper
    resp = _do_wrapper(
           ^^^^^^^^^^^^
  File "C:\Users\Lucas\dev\Pos Eng Soft Puc RJ\mvp-1\api\env\Lib\site-packages\flask_openapi3\do_wrapper.py", line 135, in _do_wrapper
    response = func(**request_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lucas\dev\Pos Eng Soft Puc RJ\mvp-1\api\app.py", line 133, in add_schedule
    print("REQUEST" + request)
          ~~~~~~~~~~^~~~~~~~~
  File "C:\Users\Lucas\dev\Pos Eng Soft Puc RJ\mvp-1\api\env\Lib\site-packages\werkzeug\local.py", line 335, in r_op
    return op(other, obj)
           ^^^^^^^^^^^^^^
TypeError: can only concatenate str (not "Request") to str
[2023-07-10 20:23:31,237] INFO _log() L224  127.0.0.1 - - [10/Jul/2023 20:23:31] "[35m[1mPOST /schedule HTTP/1.1[0m" 500 - - call_trace=C:\Users\Lucas\dev\Pos Eng Soft Puc RJ\mvp-1\api\env\Lib\site-packages\werkzeug\_internal.py L224 
[2023-07-10 20:24:00,998] INFO _log() L224   * Detected change in 'C:\\Users\\Lucas\\dev\\Pos Eng Soft Puc RJ\\mvp-1\\api\\app.py', reloading - call_trace=C:\Users\Lucas\dev\Pos Eng Soft Puc RJ\mvp-1\api\env\Lib\site-packages\werkzeug\_internal.py L224 
[2023-07-10 20:24:01,102] INFO _log() L224   * Restarting with stat - call_trace=C:\Users\Lucas\dev\Pos Eng Soft Puc RJ\mvp-1\api\env\Lib\site-packages\werkzeug\_internal.py L224 
[2023-07-10 20:24:06,698] INFO _log() L224   * Detected change in 'C:\\Users\\Lucas\\dev\\Pos Eng Soft Puc RJ\\mvp-1\\api\\app.py', reloading - call_trace=C:\Users\Lucas\dev\Pos Eng Soft Puc RJ\mvp-1\api\env\Lib\site-packages\werkzeug\_internal.py L224 
[2023-07-10 20:24:06,886] INFO _log() L224   * Restarting with stat - call_trace=C:\Users\Lucas\dev\Pos Eng Soft Puc RJ\mvp-1\api\env\Lib\site-packages\werkzeug\_internal.py L224 
[2023-07-10 20:24:08,906] INFO _log() L224  127.0.0.1 - - [10/Jul/2023 20:24:08] "OPTIONS /schedule HTTP/1.1" 200 - - call_trace=C:\Users\Lucas\dev\Pos Eng Soft Puc RJ\mvp-1\api\env\Lib\site-packages\werkzeug\_internal.py L224 
[2023-07-10 20:24:09,200] INFO _log() L224  127.0.0.1 - - [10/Jul/2023 20:24:09] "[35m[1mPOST /schedule HTTP/1.1[0m" 500 - - call_trace=C:\Users\Lucas\dev\Pos Eng Soft Puc RJ\mvp-1\api\env\Lib\site-packages\werkzeug\_internal.py L224 
